var questions = [
    {
        question1: "What does DOM stand for?",
        choices1: ["Domain Obsessive Monitor", "Double Object Mains", "Domain of Model"],
        correctAnswer1: "Domain Object Model" (alert) // not sure if this is right but wanted to have the right answer display itself when needed

    },
    {
        question2: "What does Const do? ",
        choices2: ["Const allows the varible to change its value", "Const makes the code 'considerate' and in keeping with accessibility", "Const ensures that the variable is unchangable"],
        correctAnswer2: "Const ensures that the variable is unchangable" (alert) //?
      
    },
    {
        question3: "what does API stand for?",
        choices3: ["Application Programable Interface", "Application Progress Interface", "Applicable Program Intro"],
        correctAnswer3: "Application Programable Interface" (alert) //?
        
    },
    {
        question4: "What how can you add information to an array?",
        choices4: [".new-item()", ".add()", ".append()"],
        correctAnswer4: ".append()" (alert)//?
       
    },
    {
        question5: "What information type returns either true or false?",
        choices5: ["boolean", "string", "number"],
        correctAnswer5: "Application Programable Interface" (alert)//?
      
    },
    {
        question5: "What ",
        choices5: ["boolean", "string", "number"],
        correctAnswer5: "Application Programable Interface" (alert)//?
  
    }
];




   
// below is super brief pseudo code for the challenge requirements.
// Timer = set limit, count down 1000 ms each time, subtrack 10 seconds for each wrong answer, sound affect for right or wrong answer, game ends when timer reaches 0 or when all questions are answered






