var questions = [
    {
        question1: "What does DOM stand for?",
        choices1: ["Domain Obsessive Monitor", "Double Object Model", "Document Object Model"],
        correctAnswer1: "Document Object Model" 
    },
    {
        question2: "What does Const do? ",
        choices2: ["Const allows the varible to change its value", "Const makes the code 'considerate' and in keeping with accessibility", "Const ensures that the variable is unchangable"],
        correctAnswer2: "Const ensures that the variable is unchangable" 
    },
    {
        question3: "what does API stand for?",
        choices3: ["Application Programable Interface", "Application Progress Interface", "Applicable Program Intro"],
        correctAnswer3: "Application Programable Interface" 
    },
    {
        question4: "What how can you add information to an array?",
        choices4: [".new-item()", ".add()", ".append()"],
        correctAnswer4: ".append()" 
    },
    {
        question5: "What information type returns either true or false?",
        choices5: ["boolean", "string", "number"],
        correctAnswer5: "Application Programable Interface" 
    },
    {
        question5: "Which operator is 'strict' equals?",
        choices5: ["=", "===", "=="],
        correctAnswer5: "===" 
    }
];




   
// below is super brief pseudo code for the challenge requirements.
// Timer = set limit, count down 1000 ms each time, subtrack 10 seconds for each wrong answer, sound affect for right or wrong answer, game ends when timer reaches 0 or when all questions are answered






